apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-ops-config
  namespace: sales-ns
rules:
- apiGroups: ["", "apps", "batch"]
  resources: ["deployments","statefulsets","daemonsets","jobs","cronjobs",
              "services","configmaps","persistentvolumeclaims","pods","pods/log"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: [""]  # логи подов
  resources: ["pods","pods/log"]
  verbs: ["get","list","watch"]


