apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-readonly-binding
  labels:
    app.kubernetes.io/managed-by: rbac
subjects:
  - kind: Group
    name: auditors              # аудиторы
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: product-managers      # менеджеры продуктов
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: business-analysts     # бизнес-аналитики
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-readonly
  apiGroup: rbac.authorization.k8s.io