apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-analyst-secrets
subjects:
  - kind: User
    name: security_analyst          # учётка, созданная через client-cert
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-secrets-viewer      # существующий ClusterRole
  apiGroup: rbac.authorization.k8s.io